---

dist: focal

stages:
  - test

jobs:
  include:
    - stage: test
      language: minimal
      before_script:
        - echo 'nameserver 9.9.9.10' | sudo tee /etc/resolv.conf
        - echo 'nameserver 77.88.8.8' | sudo tee -a /etc/resolv.conf
        - echo 'nameserver 168.95.1.1' | sudo tee -a  /etc/resolv.conf
        - touch failed-domain
      script:
        - for domain in `grep -v -E '^(#|$)' list`; do nslookup $domain > /dev/null || echo "$domain" | tee -a failed-domain; done
        - for domain in `cat failed-domain`; do nslookup $domain; done
        - if [ "$(wc -l failed-domain | awk '{print $1}')" -gt "0" ]; then echo "Failed domain(s):"; cat failed-domain; exit 1; fi
